databases:
  - name: sifat-portfolio-db
    databaseName: portfolio
    user: portfolio
    plan: starter

services:
  - type: web
    name: sifat-portfolio-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sifat-portfolio-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_SSL
        value: "True"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    preDeployCommand: node backend/dist/migrate.js